# Generated by Django 5.2.5 on 2025-10-25 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_ink', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='authors',
            field=models.ManyToManyField(through='django_comments_ink.CommentReactionAuthor', through_fields=('reaction', 'author'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='vote',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='objectreaction',
            name='authors',
            field=models.ManyToManyField(through='django_comments_ink.ObjectReactionAuthor', through_fields=('reaction', 'author'), to=settings.AUTH_USER_MODEL),
        ),
    ]
